Aplicacao/Models/VendaViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace sistema_loja_venda.Models
{
    public class VendaViewModel
    {
        public int? Codigo { get; set; }

        [Required(ErrorMessage = "Informe a data da venda!")]
        public DateTime? Data { get; set; }

        [Required(ErrorMessage = "Informe o cliente!")]
        public int? Codigo_cliente { get; set; }     
        public IEnumerable<SelectListItem> ListaClientes { get; set; }
        public IEnumerable<SelectListItem> ListaProdutos { get; set; }
        public string JsonProdutos { get; set; }
        public decimal Total { get; set; }
  
    }
}

Aplicacao/Controllers/VendaController.cs
using Microsoft.AspNetCore.Mvc;
using Aplicacao.Servico.Interfaces;
using sistema_loja_venda.Models;


namespace sistema_loja_venda.Controllers
{
    public class VendaController : Controller
    {
        readonly IServicoAplicacaoVenda ServicoAplicacaoVenda;
        readonly IServicoAplicacaoProduto ServicoAplicacaoProduto;
        readonly IServicoAplicacaoCliente ServicoAplicacaoCliente;


        public VendaController(
            IServicoAplicacaoVenda servicoAplicacaoVenda,
            IServicoAplicacaoProduto servicoAplicacaoProduto,
            IServicoAplicacaoCliente servicoAplicacaoCliente) // O objeto ApplicationDbContext está sendo injetado no construtor da classe CategoriaController...
        {
            ServicoAplicacaoVenda = servicoAplicacaoVenda;
            ServicoAplicacaoProduto = servicoAplicacaoProduto;
            ServicoAplicacaoCliente = servicoAplicacaoCliente;
        }
        public IActionResult Index()
        {
            return View(ServicoAplicacaoVenda.Listagem());
        }

        [HttpGet]
        public IActionResult Cadastro(int? id)
        {
            VendaViewModel viewModel = new VendaViewModel();

            if (id != null)
            {
                viewModel = ServicoAplicacaoVenda.CarregarRegistro((int)id);
            }

            viewModel.ListaClientes = ServicoAplicacaoCliente.ListaClientesDropDownList();
            viewModel.ListaProdutos = ServicoAplicacaoProduto.ListaProdutosDropDownList();

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Cadastro(VendaViewModel entidade)
        {
            if (ModelState.IsValid)
            {
                ServicoAplicacaoVenda.Cadastrar(entidade);
            }
            else
            {
                entidade.ListaClientes = ServicoAplicacaoCliente.ListaClientesDropDownList();
                entidade.ListaProdutos = ServicoAplicacaoProduto.ListaProdutosDropDownList();
                return View(entidade);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]

        public IActionResult Excluir(int id)
        {
            ServicoAplicacaoVenda.Excluir(id);
            return RedirectToAction("Index");
        }

        [HttpGet("LerValorProduto/{CodigoProduto}")]
        public decimal LerValorProduto(int CodigoProduto)
        {
            return (decimal)ServicoAplicacaoProduto.CarregarRegistro(CodigoProduto).Valor;
        }
    }   

}

Aplicacao/Views/Venda/Cadastro.cshtml
@{
    ViewData["title"] = "Cadastro | Vendas";
}

<h2>Venda</h2>
<hr />

@model sistema_loja_venda.Models.VendaViewModel

@{
    var disabled = (Model.Codigo == null) ? "disabled" : string.Empty;
}

<form asp-controller="Venda" asp-action="Cadastro" method="post">
    <input type="hidden" asp-for="Codigo" value="@Model.Codigo" />

    <div class="form-group">
        <div class="col-4">
            <label>Data</label>
            <input asp-for="Data" type="date" value="@Model.Data" class="form-control" />
            <span asp-validation-for="Data" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-4">
            <label>Cliente</label>
            <select asp-for="Codigo_cliente" asp-items="@Model.ListaClientes" class="form-control" input-lg></select>
            <span asp-validation-for="Codigo_cliente" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-4">
            <label>Produtos</label>
            <select id="cboProduto" onchange="BuscarPrecoProduto()" asp-items="@Model.ListaProdutos" class="form-control" input-lg></select>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-2">
            <label>Preço unitário</label>
            <input id="txtPrecoUnitario" type="number" class="form-control" disabled />
        </div>
        <div class="col-md-2">
            <label>Quantidade</label>
            <input id="txtQuantidade" type="number" class="form-control" onchange="CalcularSubTotal()" />
        </div>
        <div class="col-md-2">
            <label>Sub-Total</label>
            <input id="txtSubTotal" type="number" class="form-control" disabled />
        </div>
        <div class="col-md-2">
            <br />
            <button type="button" class="btn btn-info" onclick="AddProduto()">Adicionar</button>
            <br />
        </div>
    </div>
    <br />
<div class="form-group">
    <div class="col-md-12">
        <table class="table table-bordered">
              <thead class="thread-inverse">
                   <tr style="background-color:#f6f6f6;">
                       <th>Produto</th>
                       <th>Preço Unitário</th>
                       <th>Quantidade</th>
                       <th>Total</th>
                   </tr>
              </thead>
            <tbody id="gridProdutos"></tbody>   
        </table>
    </div>
</div>

<div class="form-group">
    <div class="col-md-3">
          <label>Total</label>
          <input id="txtTotal" asp-for="Total" type="text" value="@Model.Total" class="form-control" />   
          <span asp-validation-for="Total" class="text-danger"></span>
    </div>

    <textarea asp-for="JsonProdutos" id="txtJsonProdutos" class="col" style="display : none;"></textarea>

    <br />
    <div class="col">
          <button type="button" class="btn btn-info" onclick="Novo()">Novo</button>
          <button type="submit" class="btn btn-success">Gravar</button>
          <button type="button" class="btn btn-warning" onclick="Listagem()">Listagem</button>
          <button type="button" class="btn btn-danger" onclick="Excluir(@Model.Codigo)" @disabled>Excluir</button>
    </div>
</div>
</form>

<script>
    var Items = new Object();
    Items.Produtos = new Array();
    var gridProdutos = document.getElementById("gridProdutos");

    function fixaDuasCasasDecimais(num) {
        return parseFloat(Math.round(num * 100) / 100).toFixed(2);
    }

    function AddProduto() {
        var CodigoProduto = document.getElementById("cboProduto")
        var Quantidade = document.getElementById("txtQuantidade").value;
        var ValorUnitario = document.getElementById("txtPrecoUnitario").value;
        var SubTotal = document.getElementById("txtSubTotal").value;

        Items.Produtos.push({
            "Codigo_produto": CodigoProduto.value,
            "Quantidade": Quantidade,
            "Valor_unitario": ValorUnitario,
            "Valor_total": SubTotal
        });

        document.getElementById("txtJsonProdutos").value = JSON.stringify(Items.Produtos);

       //console.log(JSON.stringify(Items.Produtos)); // Console do navegador do JS.

        var linhaGrid =
            "<tr id ='" + CodigoProduto.value + "'>" +
            "<td>" + CodigoProduto.options[CodigoProduto.selectedIndex].text + "</td>" +
            "<td>" + ValorUnitario + "</td>" +
            "<td>" + Quantidade + "</td>" +
            "<td> R$ " + SubTotal + "</td>" +
            "</tr>";

        gridProdutos.innerHTML += linhaGrid;

        var Total = Number(document.getElementById("txtTotal").value.toString().replace(",", ".")) + Number(SubTotal);
        document.getElementById("txtTotal").value = fixaDuasCasasDecimais(Total).replace(".",",");

        document.getElementById("txtQuantidade").value = "";
        document.getElementById("txtSubTotal").value = "";
        document.getElementById("txtPrecoUnitario").value = "";
        document.getElementById("cboProduto").selectedindex = -1;

    }

    function CalcularSubTotal() {
        var PrecoUnitario = document.getElementById("txtPrecoUnitario").value;
        var SubTotal = PrecoUnitario * document.getElementById("txtQuantidade").value;
        document.getElementById("txtSubTotal").value = fixaDuasCasasDecimais(SubTotal);

    }

    function BuscarPrecoProduto() {
        var CodigoProduto = document.getElementById("cboProduto");
        var url = `/LerValorProduto/${CodigoProduto.value}`;

        var xhr = new XMLHttpRequest();
        xhr.onreadystatechange = function () {
            if (xhr.readyState == XMLHttpRequest.DONE) {
                document.getElementById("txtPrecoUnitario").value = xhr.responseText;
                CalcularSubTotal();
            }
        }
        xhr.open('GET', url, false);
        xhr.send(null);

    }
    function Novo() {
        Request("Cadastro");
    }
    function Listagem() {
        Request("");
    }
    function Excluir(Codigo) {
        Request("Excluir\\" + Codigo);
    }
    function Request(request) {
        window.location = window.origin + "\\Venda\\" + request;
    }
</script>

Aplicacao/Views/Venda/Index.cshtml
@{
    ViewData["title"] = "Vendas";
}
@model List<sistema_loja_venda.Models.VendaViewModel>;

<h2>Vendas</h2>
<hr />

<table class="table table-bordered">
    <thead>
        <tr style="background-color:#f6f6f6">
            <th>Código</th>
            <th>Data</th>
            <th>Cliente</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
      @foreach (var item in Model)
      {
         <tr onclick="Editar(@item.Codigo)" style="cursor:pointer;">
            <td>@item.Codigo</td>
            <td>@item.Data</td>
            <td>@item.Codigo_cliente</td>
            <td>@item.Total</td>
         </tr>
      }
    </tbody>
</table>
<br />

<button type="button" class="btn btn-block btn-primary" onclick="Cadastrar()">Registrar Venda</button>

<script>
    function Editar(Codigo) {
        window.location = window.origin + "\\Venda\\Cadastro\\" + Codigo;
    }
    function Cadastrar() {
        window.location = window.origin + "\\Venda\\Cadastro";
    }

</script>